# Generated by Django 4.0.1 on 2023-04-05 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_events', '0002_rename_tag_tag_name_alter_event_image_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='tags',
            new_name='tag',
        ),
    ]
