name: Build, Test and Deploy django_react_aws backend

on:
  push:
    branches: [ master ]


jobs:
  build-test:
    name: Run build tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Injecting environment vars
      run: |
        echo "${{ secrets.TEST_SECRETS }}" >> .env
    - name: List all files
      run: |
        ls -al
  deploy:
    name: Deploying on EC2 via SSH
    if: ${{ github.event_name == 'push' }}
    needs: [build-test]
    runs-on: ubuntu-latest
    steps:
    - name: Deploying Application on EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_EC2_IP }}
        username: ${{ secrets.SSH_EC2_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script: |
          ls -al
          cd django_react_aws

