name: Build and deploy frontend
env: 
  AWS_STORAGE_BUCKET_NAME: "django-react-frontend"
  AWS_REGION_NAME: "us-east-2"
  DEPLOY_STATICFILES_NAME: "core_staticfiles"

on:
  push:
    branches: [ master ]
    
jobs:
  copy-django-static:
    name: Copy django staticfiles
    runs-on: ubuntu-latest
    needs: [build-deploy]
    defaults:
      run:
          working-directory: ./
    steps: 
      - name: Git clone on our repo
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION_NAME }}

      - name: Copying file to S3
        run: aws s3 cp ./${{ env.DEPLOY_STATICFILES_NAME }}/ s3://${{ secrets.AWS_STORAGE_BUCKET_NAME }}

      - name: Print nice message on success finish
        run: echo "CI part finished successfuly"
    
  build-deploy:
    name: Build and deploy frontend to S3
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v2

      - name: Injecting environment variables
        run: echo "REACT_APP_API_URL=${{ secrets.API_URL }}" >> .env

      - name: Installing dependencies
        run: npm install

      - name: Building project
        run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION_NAME }}

      - name: Deploy to S3 bucket
        run: aws s3 sync ./dist/ s3://${{ secrets.AWS_STORAGE_BUCKET_NAME }} --delete